### ISSUE TITLE
Vim E117 Unkown function vimside#command#completions#Run()

### ISSUE THREAD

**Issue by zenwong** [megaannum/vimside#1]
Hi I'm trying to get your plugin working, but running into Vim E117 Unknown Function vimside#command#completions#Run() error.  I am using pathogen, I have form self ensime and vimside installed.  The other vimside commands seem to be working ok.

**Comment by megaannum** [comment]
What version of Vimside (look at the top of the vimside.vim file
(and with the next upload one should look at the file vimside/version.vim))?

vimside#command#completions#Run()
Is the function Run() in the file vimside/command/completions.vim
In the latest uploaded version 0.2.5 the file and function
exists.

On 11/21/2012 08:00 PM, zenwong wrote:

> Hi I'm trying to get your plugin working, but running into Vim E117
> Unknown Function vimside#command#completions#Run() error. I am using
> pathogen, I have form self ensime and vimside installed. The other
> vimside commands seem to be working ok.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
How do you set up pathogen for Vimside?
I have never used it but know that many Vim users do.
Thanks.

On 11/21/2012 08:00 PM, zenwong wrote:

> Hi I'm trying to get your plugin working, but running into Vim E117
> Unknown Function vimside#command#completions#Run() error. I am using
> pathogen, I have form self ensime and vimside installed. The other
> vimside commands seem to be working ok.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
Also, when reporting an error, please include platform
(linux, microsoft, etc.), GVim or Vim and what version of Vim.
Just might help resolving the issue.
Thanks

On 11/21/2012 08:00 PM, zenwong wrote:

> Hi I'm trying to get your plugin working, but running into Vim E117
> Unknown Function vimside#command#completions#Run() error. I am using
> pathogen, I have form self ensime and vimside installed. The other
> vimside commands seem to be working ok.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1.

## 

Quis custodiet ipsos custodes

**Comment by zenwong** [comment]
I'm running on Arch Linux.

I check autoload/vimside.vim and it states it's running version 0.2.5.  It's just a standard pathogen install.  All the relevant plugins for vimside are installed under ~/.vim/bundle.

then in my .vimrc I got this at the top

set nocompatible
call pathogen#infect()
filetype off
syntax on
filetype plugin indent on

not sure if it bears any relevance but in autoload/vimside.vim the function

function! vimside#version()
  return '0.2'
endfunction

**Comment by zenwong** [comment]
I also tried sourcing the file directly in .vimrc

source ~/.vim/bundle/vimside/autoload/vimside/command/completions.vim

**Comment by zenwong** [comment]
The Run function exists in autoload/vimside/command/completions.vim

**Comment by zenwong** [comment]
Sorry forgot to mention, I'm using GVim

**Comment by megaannum** [comment]
Its a bug. In the file ftplugin/vimside.vim
change from:
setlocal omnifunc=vimside#command#completions#Run()
to
setlocal omnifunc=vimside#command#completions#Run

I will checkin a fix on Friday.

Sorry about that.

On 11/21/2012 09:35 PM, zenwong wrote:

> Sorry forgot to mention, I'm using GVim
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1#issuecomment-10624293.

## 

Quis custodiet ipsos custodes

**Comment by zenwong** [comment]
After switching the above omnifunc, I get a different error

E716 key not present in dictionary : :completions

invalid expression dic[':completions']

undefined variable completions

**Comment by zenwong** [comment]
Does the auto complete work with imports?  trying

import io.Sou < pressing c-x c-o here

results in the above error.  after importing the Source package, I can auto complete:

Source.fr < c-x c-o here

and the drop down completes find.  Also under the keymappings, I can't get the tab to call TabToOmni

function! TabToOmni()
    return "<c-x><c-o>"
endfunction
inoremap <tab> <c-r>=TabToOmni()<CR>

is this because I'm using supersnipmate?

**Comment by megaannum** [comment]
If you enter:
:inoremap
on the command line, it will list the current bindings.
On my system I see:
i  <Tab>       \* <C-G>u<C-R>=snipMate#TriggerSnippet()<CR>
If you now enter:
:inoremap <tab> <c-r>=TabToOmni()<CR>
On the command line, Vimside TAB in insert mode will
map to <c-x><c-o>.

Since so many people use snipmate, I will have to find
a better solution.

On 11/21/2012 11:03 PM, zenwong wrote:

> Does the auto complete work with imports? trying
> 
> import io.Sou < pressing c-x c-o here
> 
> results in the above error. after importing the Source package, I can
> auto complete:
> 
> Source.fr < c-x c-o here
> 
> and the drop down completes find. Also under the keymappings, I can't
> get the tab to call TabToOmni
> 
> function! TabToOmni()
> return "<c-x><c-o>"
> endfunction
> inoremap =TabToOmni()
> 
> is this because I'm using supersnipmate?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1#issuecomment-10625404.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
Its a bug. Check in fix on Friday.

On 11/21/2012 10:04 PM, zenwong wrote:

> After switching the above omnifunc, I get a different error
> 
> E716 key not present in dictionary : :completions
> 
> invalid expression dic[':completions']
> 
> undefined variable completions
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/1#issuecomment-10624663.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
Fixed with today's checkin.
