### ISSUE TITLE
Import file under cursor

### ISSUE THREAD

**Issue by ryskajakub** [megaannum/vimside#15]
Hi, I'm trying to import file under cursor, I hover over **Try** and type **\vi** in this file with hope, that it will be imported automatically. There is a list of suggested imports, so I choose the first one: **scala.util.Try**

```
object Main {
  def main (args:Array[String]) {
    println("ahoj")
    val x = List("abc")
    val y = Try("5")
  }
}
```

But nothing is imported, I just see an error:

```
java.lang.NoSuchMethodError: scala.Predef$ArrowAssoc$.extension$$u2192(Ljava/lan
g/Object;Ljava/lang/Object;)Lscala/Tuple2; 
```

In ensime log: there is:

```
Writing: (:return (:ok (:procedure-id 20 :status failure :reason "java.lang.    NoSuchMethodError: scala.Predef$ArrowAssoc$.extension$$u2192(Ljava/lang/Obje    ct;Ljava/lang/Object;)Lscala/Tuple2;")) 31)
```

I've just downloaded everything today, so I'm using the latest ensime: **ensime_2.10.0-RC3-0.9.8.2** and vimside.
Thanks for helping me with this issue.

**Comment by megaannum** [comment]
latest version of Ensime is:
ensime_2.10.0-0.9.8.5

What version of Scala are you using?

I hope one of the above helps because otherwise its a bug
in Ensime which I have treated as a black-box while
creating Vimside.

megaannum

On 03/04/2013 05:01 AM, coubeatczech wrote:

> Hi, I'm trying to import file under cursor, I hover over _Try_ and type
> _\vi_ in this file with hope, that it will be imported automatically.
> There is a list of suggested imports, so I choose the first one:
> _scala.util.Try_
> 
> |object Main {
>    def main (args:Array[String]) {
>      println("ahoj")
>      val x = List("abc")
>      val y = Try("5")
>    }
> }
> |
> 
> But nothing is imported, I just see an error:
> 
> |java.lang.NoSuchMethodError: scala.Predef$ArrowAssoc$.extension$$u2192(Ljava/lan
> g/Object;Ljava/lang/Object;)Lscala/Tuple2;
> |
> 
> In ensime log: there is:
> 
> |Writing: (:return (:ok (:procedure-id 20 :status failure :reason "java.lang.    NoSuchMethodError: scala.Predef$ArrowAssoc$.extension$$u2192(Ljava/lang/Obje    ct;Ljava/lang/Object;)Lscala/Tuple2;")) 31)
> |
> 
> I've just downloaded everything today, so I'm using the latest ensime:
> _ensime_2.10.0-RC3-0.9.8.2_ and vimside.
> Thanks for helping me with this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/15.

## 

Quis custodiet ipsos custodes

**Comment by ryskajakub** [comment]
Hi, thanks, I got it semi-working after switching to 2.10.0.-0.9.8.9, now the file is imported, but the leading **o** from the keyword **object** in my test application disappears. But it seems to be problem of ensime, I'll ask there.
