### ISSUE TITLE
Vimside can't find port file

### ISSUE THREAD

**Issue by pjrt** [megaannum/vimside#18]
I'm getting this error when starting Vimside:

Vimside Failed to start Ensime Server port file does not exists
line   24:
E484: Can't open file /project/_ensime_port

I'm using the .ensime config created by the ensime-sbt plugin and pretty much the same examples_options_user.vim -> options_user.vim that comes with vimside.

**Comment by megaannum** [comment]
As always, what version of Vimside?

With the latest version you can turn on pre-configuration
logging to get information about where Vimside thinks it
should be looking for the port file.
Go to the Vimside plugin, plugin/vimside.vim, and, at
the bottom, change from:
let g:Vimside_Enable_Pre_Initialization_Logging = 0
to
let g:Vimside_Enable_Pre_Initialization_Logging = 1

A log file named: VIMSIDE_EARLY_LOG will be generated.

See what is in it.

On 04/10/2013 08:10 AM, Pedro Rodriguez wrote:

> I'm getting this error when starting Vimside:
> 
> Vimside Failed to start Ensime Server port file does not exists
> line 24:
> E484: Can't open file /project/_ensime_port
> 
> I'm using the .ensime config created by the ensime-sbt plugin and pretty
> much the same examples_options_user.vim -> options_user.vim that comes
> with vimside.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/18.

## 

Quis custodiet ipsos custodes

**Comment by pjrt** [comment]
Well this is strange. I turned on the logging (like you said) and that.....fixed it? It now starts up and all. I obviously did something, but I can't seem to remember doing anything else. Turning the logging off does not break it again. 

Now I'm having issues with the Type Inspector (says "Scala/Java errors and warnings"). But that is a different thing. 

Running latest vimside (2.10) and Ensime (2.10)
