### ISSUE TITLE
Getting error "Option tailor-hover-updatetime not Bool type: 600" among others when trying to set any non-boolean option

### ISSUE THREAD

**Issue by pjrt** [megaannum/vimside#19]
It happens in autoload/vimside/options/defined.vim.

It happens because a `g:OPTION_BOOLEAN_TYPE` and a `g:OPTION_NUMBER_TYPE` are the same thing (type(0) == 0).

When doing the comparison in `CheckValue`, it asks `if (type(600) != g:OPTION_NUMBER_TYPE)`, which is (0 != 0) which is false. 

Then it goes on, however, to ask `if def.type == g:OPTION_BOOLEAN_TYPE` which is (0 == 0). This is true! So then it goes on to ask if the value is either 1 or 0, which if false (it is 600) and that's when it fails. 

I tried to think of a way to fix this, but I don't see why we even asking `if def.type == g:OPTION_BOOLEAN_TYPE`. For numbers, it should just be numbers, for bool, it is either 0 (false) or >0 (true). 

I say we just get rid of the last check (the part where it compares the bool type to the number type) since it is useless. I did this in my fork but wanted to discuss it in case there is a reason we have this (that I missed).

**Comment by megaannum** [comment]
Checked in fix - removed check as suggested.
Next release will remove commented out code.
