### ISSUE TITLE
TimeTrigger: Key not present in Dictionary: decl-as

### ISSUE THREAD

**Issue by ceedubs** [megaannum/vimside#20]
I'm just trying to get started with vimside. If I can get it up and running, I will most likely be spending 10+ hours a day using it :). Thank you for the time you have spent developing it and thoroughly documenting the setup process. I tried to follow it exactly, but I'm still encountering some issues. I installed using Pathogen (so I should be on the latest commit on master: https://github.com/megaannum/vimside/commit/a0d69149ed6ebfe3be57cf5fe1b8e8066b8a5c69) on Mac OS X 10.8.3. The command to start up Ensime seems to be working just fine, but when I try to make calls to either vimside#command#InspectTypeAtPoint() or vimside#command#SymbolAtPoint(), I get errors.

When I call through to vimside#command#SymbolAtPoint(), `Scala/Java errors and warnings` displays at the bottom of the screen.

When I call through to vimside#command#InspectTypeAtPoint(), I get this:

> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point..<SNR>89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..<SNR>89_TypeInspector_constructor..<SNR>89_TypeInspector_init:
> line   13:
> E716: Key not present in Dictionary: :decl-as
> "Inspector" [New File]
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point..<SNR>89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..g:history_and_do..<SNR>89_DoTypeInspector..<SNR>89_loadDisplay..<SNR>89_BuildDisplay..<SN
> R>89_TypeInspector_render..<SNR>89_inspector_insert_linked_type..vimside#command#show_doc_symbol_at_point#MakeUrl:
> line   31:
> E121: Undefined variable: url
> E15: Invalid expression: [found, url]
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point..<SNR>89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..g:history_and_do..<SNR>89_DoTypeInspector..<SNR>89_loadDisplay..<SNR>89_BuildDisplay:
> line    7:
> E171: Missing :endif
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point..<SNR>89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous:
> line   62:
> E171: Missing :endif
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point..<SNR>89_type_inspect_info_at_point:
> line   21:
> E171: Missing :endif
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..<SNR>89_inspect_type_at_point:
> line    9:
> E171: Missing :endif
> Error detected while processing function vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point:
> line    5:
> E171: Missing :endif
> Error detected while processing function vimside#command#InspectTypeAtPoint:
> line    2:
> E171: Missing :endif

When I inspect the VIMSIDE_LOG afterwards, I see the following:

> ERROR: 20130504-100842: TimeTrigger: Vim(if):E715: Dictionary required at function vimside#scheduler#TimeTrigger..vimside#PingEnsimeServer..vimside#ensime#io#ping..vimside#ensime#swank#handle..<SNR>71_HandleResponse..g:SymbolAtPointHandler_Ok, line 8
> ERROR: 20130504-100949: TimeTrigger: Vim(let):E716: Key not present in Dictionary: :decl-as at function vimside#scheduler#TimeTrigger..vimside#PingEnsimeServer..vimside#ensime#io#ping..vimside#ensime#swank#handle..<SNR>71_HandleResponse..g:type_inspector_show..<SNR>85_TypeInspector_constructor..<SNR>85_TypeInspector_init, line 13

Here is my bash version: GNU bash, version 4.2.45(2)-release (i386-apple-darwin12.3.0).

**Comment by megaannum** [comment]
Concerning the message:
  Scala/Java errors and warnings

This is displayed when there are compile errors in one or more files.
To see the errors in a quickfix window enter the command:

vimside#command#ShowErrorsAndWarning().

In the plugin/vimside.vim file this is aliased to the key shortcut:

"   (Re-)Show all errors and warnings in the project.
autocmd FileType scala nmap <silent> <Leader>ve :call 
vimside#command#ShowErrorsAndWarning()<CR>

In the file inspector.vim, at line 1073 (line 13 in the function
TypeInspector_init as shown in the stack trace), if you
replace the line:

   let self.decl_as = self.type_info[":decl-as"]

with the lines:

   if has_key(self.type_info, ":decl-as")
     let self.decl_as = self.type_info[":decl-as"]
   endif

and see if that fixes the problem. If so I will check in the change.
You must have been "inspecting" something that did not have a
declaration???, I don't know. I might not have all of the possible
variations in what the Ensime Server can return when asked to
do a type inspection.
Thanks. Let me know.

-- You are luck (at least I think so) to get to write Scala
10 hours a day. I can only write Scala at home; they do not
use Scala where I work.

On 05/04/2013 07:24 AM, Cody Allen wrote:

> I'm just trying to get started with vimside. If I can get it up and
> running, I will most likely be spending 10+ hours a day using it :).
> Thank you for the time you have spent developing it and thoroughly
> documenting the setup process. I tried to follow it exactly, but I'm
> still encountering some issues. I installed using Pathogen (so I should
> be on the latest commit on master: a0d6914
> https://github.com/megaannum/vimside/commit/a0d69149ed6ebfe3be57cf5fe1b8e8066b8a5c69)
> on Mac OS X 10.8.3. The command to start up Ensime seems to be working
> just fine, but when I try to make calls to either
> vimside#command#InspectTypeAtPoint() or vimside#command#SymbolAtPoint(),
> I get errors.
> 
> When I call through to vimside#command#SymbolAtPoint(), |Scala/Java
> errors and warnings| displays at the bottom of the screen.
> 
> When I call through to vimside#command#InspectTypeAtPoint(), I get this:
> 
> ```
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point..89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..89_TypeInspector_constructor..89_TypeInspector_init:
> line 13:
> E716: Key not present in Dictionary: :decl-as
> "Inspector" [New File]
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point..89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..g:history_and_do..89_DoTypeInspector..89_loadDisplay..89_BuildDisplay..
> R>89_TypeInspector_render..89_inspector_insert_linked_type..vimside#command#show_doc_symbol_at_point#MakeUrl:
> line 31:
> E121: Undefined variable: url
> E15: Invalid expression: [found, url]
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point..89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous..g:type_inspector_show..g:history_and_do..89_DoTypeInspector..89_loadDisplay..89_BuildDisplay:
> line 7:
> E171: Missing :endif
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point..89_type_inspect_info_at_point..vimside#swank#rpc#i
> nspect_type_at_point#Run..vimside#ensime#swank#dispatch..vimside#ensime#swank#asynchronous:
> line 62:
> E171: Missing :endif
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point..89_type_inspect_info_at_point:
> line 21:
> E171: Missing :endif
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point..89_inspect_type_at_point:
> line 9:
> E171: Missing :endif
> Error detected while processing function
> vimside#command#InspectTypeAtPoint..vimside#command#inspector#type_at_point:
> line 5:
> E171: Missing :endif
> Error detected while processing function
> vimside#command#InspectTypeAtPoint:
> line 2:
> E171: Missing :endif
> ```
> 
> When I inspect the VIMSIDE_LOG afterwards, I see the following:
> 
> ```
> ERROR: 20130504-100842: TimeTrigger: Vim(if):E715: Dictionary
> required at function
> vimside#scheduler#TimeTrigger..vimside#PingEnsimeServer..vimside#ensime#io#ping..vimside#ensime#swank#handle..71_HandleResponse..g:SymbolAtPointHandler_Ok,
> line 8
> ERROR: 20130504-100949: TimeTrigger: Vim(let):E716: Key not present
> in Dictionary: :decl-as at function
> vimside#scheduler#TimeTrigger..vimside#PingEnsimeServer..vimside#ensime#io#ping..vimside#ensime#swank#handle..71_HandleResponse..g:type_inspector_show..85_TypeInspector_constructor..85_TypeInspector_init,
> line 13
> ```
> 
> Here is my bash version: GNU bash, version 4.2.45(2)-release
> (i386-apple-darwin12.3.0).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/20.

## 

Quis custodiet ipsos custodes

**Comment by ceedubs** [comment]
@megaannum thank you for the really fast reply. I tried making the suggested patch to inspector.vim. It made that individual error message go away, but other error messages remain. I think that missing key was just an artifact of a bigger problem. When I look at the errors in the quickfix window as you suggested, there are a slew of them. They begin with saying a bunch of packages don't exist that are certainly there. It's an SBT project that compiles fine with an `sbt compile` command. I wonder if there is an issue with the .ensime file being generated by https://github.com/aemoncannon/ensime-sbt-cmd . I'm very new to using Ensime, so it's possible that I am doing doing something pretty silly.

> You are luck (at least I think so) to get to write Scala 10 hours a day. I can only write Scala at home; they do not use Scala where I work.

I agree; I used to write Java code for a living, and writing Scala code is much more enjoyable. I work (remotely) for a San-Francisco based startup called Reverb: https://helloreverb.com/#developers and we are doing some pretty cool things. We are always looking for good Scala developers, so shoot me an email at cody@helloreverb.com if you are interested.

**Comment by ceedubs** [comment]
A coworker who is familiar with Ensime is helping me try to get down to the bottom of this. I'll leave this issue open for now, and hopefully once I figure out what the problem is, I can add some info to the README.

**Comment by megaannum** [comment]
As an aid to see whats happening prior to all of the Options
being loaded (and, therefore, enabling the standard Vimside
logger), at the bottom of the plugin/vimside.vim file there
is a value:

let g:Vimside_Enable_Pre_Initialization_Logging = 0

If this is set to true,

let g:Vimside_Enable_Pre_Initialization_Logging = 1

then during pre-logging startup, information is printed to
a file called

let g:Vimside_Enable_Pre_Initialization_Logging_File = 'VIMSIDE_EARLY_LOG'

in the local directory. Sometimes this helps see when/where/what
is being set.

On 05/04/2013 09:32 AM, Cody Allen wrote:

> A coworker who is familiar with Ensime is helping me try to get down to
> the bottom of this. I'll leave this issue open for now, and hopefully
> once I figure out what the problem is, I can add some info to the README.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/20#issuecomment-17437055.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
Just a thought, there is an Option generally set in

options_project.vim

called

   call owner.Set("ensime-config-file-name", "ensime_config.vim")

but the ensime SBT creates a file called ".ensime".

On 05/04/2013 09:06 AM, Cody Allen wrote:

> @megaannum https://github.com/megaannum thank you for the really fast
> reply. I tried making the suggested patch to inspector.vim. It made that
> individual error message go away, but other error messages remain. I
> think that missing key was just an artifact of a bigger problem. When I
> look at the errors in the quickfix window as you suggested, there are a
> slew of them. They begin with saying a bunch of packages don't exist
> that are certainly there. It's an SBT project that compiles fine with an
> |sbt compile| command. I wonder if there is an issue with the .ensime
> file being generated by https://github.com/aemoncannon/ensime-sbt-cmd .
> I'm very new to using Ensime, so it's possible that I am doing doing
> something pretty silly.
> 
> ```
> You are luck (at least I think so) to get to write Scala 10 hours a
> day. I can only write Scala at home; they do not use Scala where I work.
> ```
> 
> I agree; I used to write Java code for a living, and writing Scala code
> is much more enjoyable. I work (remotely) for a San-Francisco based
> startup called Reverb: https://helloreverb.com/#developers and we are
> doing some pretty cool things. We are always looking for good Scala
> developers, so shoot me an email at cody@helloreverb.com
> mailto:cody@helloreverb.com if you are interested.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/20#issuecomment-17436649.

## 

Quis custodiet ipsos custodes

**Comment by ceedubs** [comment]
The VIMSIDE_EARLY_LOG showed what I would expect, and calling `owner.Set("ensime-config-file-name", ".ensime")` didn't seem to help at all. However, I have that being called in options_user.vim, not in options_project.vim. I wasn't going to try to mess with any project-specific configuration until I had things up and running. Is it necessary to set up an options_project.vim?

**Comment by megaannum** [comment]
No, options_project.vim is used if you have multiple projects
and you want different behavior per-project or if you are part
of a team and the team has some standard behavior for the project.

On 05/06/2013 05:12 AM, Cody Allen wrote:

> The VIMSIDE_EARLY_LOG showed what I would expect, and calling
> |owner.Set("ensime-config-file-name", ".ensime")| didn't seem to help at
> all. However, I have that being called in options_user.vim, not in
> options_project.vim. I wasn't going to try to mess with any
> project-specific configuration until I had things up and running. Is it
> necessary to set up an options_project.vim?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/20#issuecomment-17478355.

## 

Quis custodiet ipsos custodes

**Comment by megaannum** [comment]
Do you have logging enabled for  the Ensime server?
Set the Option

ensime-log-enabled

to true (1). The default name of the file will be

ENSIME_LOG

See if there are any errors in its listing.
FYI: I do not control how/what the Ensime server logs
but it does report errors.

On 05/06/2013 05:12 AM, Cody Allen wrote:

> The VIMSIDE_EARLY_LOG showed what I would expect, and calling
> |owner.Set("ensime-config-file-name", ".ensime")| didn't seem to help at
> all. However, I have that being called in options_user.vim, not in
> options_project.vim. I wasn't going to try to mess with any
> project-specific configuration until I had things up and running. Is it
> necessary to set up an options_project.vim?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/20#issuecomment-17478355.

## 

Quis custodiet ipsos custodes

**Comment by ceedubs** [comment]
I checked out the ENSIME_LOG, and I'm still not sure what the trouble is. Nobody else seems to have the same issue, and it will probably be a while before I come back to trying to get this to work, so I'm going to go ahead and close out this issue. Thanks for all the help debugging, @megaannum .
