### ISSUE TITLE
Custom-built ensime breaks Scala version detection in manager.vim

### ISSUE THREAD

**Issue by opyate** [megaannum/vimside#25]
When custom-building ensime using `sbt stage`, it generates something like `dist_2.10.2` in the current directory.

When configuring vimside with `ensime.dist.dir=dist_2.10.2`, it breaks the call to `matchlist` on line 642 in `autoload/vimside/options/manager.vim` which expects something of the form `"ensime_2.9.2-0.9.8.9"` instead.

A work-around currently is to do this after the stage:

```
mv dist_2.10.2 dist_2.10.2-x
```

...and then configure vimside with this new fake value instead.

**Comment by megaannum** [comment]
Thanks.
Richard

On 10/23/2013 09:23 AM, Juan M Uys wrote:

> Closed #25 https://github.com/megaannum/vimside/issues/25.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/25.

## 

Quis custodiet ipsos custodes
