### ISSUE TITLE
Failure on Ensime startup (probably because vimside isn't configured correctly)

### ISSUE THREAD

**Issue by leifwickland** [megaannum/vimside#7]
I thought I'd followed the directions in the readme to get vimside setup correctly. I installed the dependencies. I configured a options_user.vim.  However, when attempt to start Ensime with <Leader>vs I get the following pile of errors:

```
Starting Ensime Engine ...
Error detected while processing function vimside#command#StartEnsime..vimside#command#ensime#Start..vimside#StartEnsime..vimside#options#manager#Load:
line  185:
E121: Undefined variable: l:ensime_config_dir
E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
line  197:
E121: Undefined variable: portdir
E15: Invalid expression: portdir . '/' . l:pfilename
line  198:
E121: Undefined variable: value
E116: Invalid arguments for function vimside#options#manager#SetOption
line  243:
E121: Undefined variable: l:ensime_config_dir
E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
line  254:
E121: Undefined variable: logdir
E15: Invalid expression: logdir . '/' . lfname
line  256:
E121: Undefined variable: value
E116: Invalid arguments for function vimside#options#manager#SetOption
line  281:
E121: Undefined variable: l:ensime_config_dir
E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
line  292:
E121: Undefined variable: logdir
E15: Invalid expression: logdir . '/' . lfname
line  294:
E121: Undefined variable: value
E116: Invalid arguments for function vimside#options#manager#SetOption
Error detected while processing function vimside#command#StartEnsime..vimside#command#ensime#Start..vimside#StartEnsime:
line   17:
E605: Exception not caught: Option Load Errors: ['Option ''ensime-install-path'' is not directory: ''/home/lwickland/.vim/vim-addons/ensime''', 'Option not found: ''test-ensime-file-dir''', 'Could not load ensime config file: ''ensime_config.vim''', 'Not a directory: ''/home/lwickland/.vim/vim-addons/ensime''', 'Not a directory: ''/home/lwickland/.vim/vim-addons/ensime/ensime_2.9.2-0.9.8.1''', 'No Ensime Distribution path, set options ''ensime-install-path'' or ''ensime-dist-path''']
```

This is probably because I didn't configure something right. Would you be willing to help me, please?

**Comment by megaannum** [comment]
Vimside while validating the Options, adds each error to
an array of errors. Then if there are any errors, and Exception
is thrown (preventing any processing beyond Option validation).
When the Exception is printed out, the first error is printed
first.
So, looking at the line:
E605: Exception not caught .....
the first error encountered is that the value of the Option
ensime-install-path
/home/lwickland/.vim/vim-addons/ensime
is not a directory on your system.

The VimL code that does this checking is in the
autoload/vimside/options/manager.vim file:

function! s:CheckDirectoryPathKind(def, value, errors)
   let def = a:def
   let value = a:value
   let errors = a:errors

   if ! isdirectory(value)
     call add(errors, "Option '". def.name ."' is not directory: '" 
.value ."'")
   endif
endfunction

Richard
On 01/03/2013 04:23 PM, Leif Wickland wrote:

> I thought I'd followed the directions in the readme to get vimside setup
> correctly. I installed the dependencies. I configured a
> options_user.vim. However, when attempt to start Ensime with vs I get
> the following pile of errors:
> 
> |Starting Ensime Engine ...
> Error detected while processing function vimside#command#StartEnsime..vimside#command#ensime#Start..vimside#StartEnsime..vimside#options#manager#Load:
> line  185:
> E121: Undefined variable: l:ensime_config_dir
> E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
> E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
> line  197:
> E121: Undefined variable: portdir
> E15: Invalid expression: portdir . '/' . l:pfilename
> line  198:
> E121: Undefined variable: value
> E116: Invalid arguments for function vimside#options#manager#SetOption
> line  243:
> E121: Undefined variable: l:ensime_config_dir
> E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
> E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
> line  254:
> E121: Undefined variable: logdir
> E15: Invalid expression: logdir . '/' . lfname
> line  256:
> E121: Undefined variable: value
> E116: Invalid arguments for function vimside#options#manager#SetOption
> line  281:
> E121: Undefined variable: l:ensime_config_dir
> E116: Invalid arguments for function filewritable(l:ensime_config_dir) == 2
> E15: Invalid expression: filewritable(l:ensime_config_dir) == 2
> line  292:
> E121: Undefined variable: logdir
> E15: Invalid expression: logdir . '/' . lfname
> line  294:
> E121: Undefined variable: value
> E116: Invalid arguments for function vimside#options#manager#SetOption
> Error detected while processing function vimside#command#StartEnsime..vimside#command#ensime#Start..vimside#StartEnsime:
> line   17:
> E605: Exception not caught: Option Load Errors: ['Option ''ensime-install-path'' is not directory: ''/home/lwickland/.vim/vim-addons/ensime''', 'Option not found: ''test-ensime-file-dir''', 'Could not load ensime config file: ''ensime_config.vim''', 'Not a directory: ''/home/lwickland/.vim/vim-addons/ensime''', 'Not a directory: ''/home/lwickland/.vim/vim-addons/ensime/ensime_2.9.2-0.9.8.1''', 'No Ensime Distribution path, set options ''ensime-install-path'' or ''ensime-dist-path''']
> |
> 
> This is probably because I didn't configure something right. Would you
> be willing to help me, please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/megaannum/vimside/issues/7.

## 

Quis custodiet ipsos custodes

**Comment by leifwickland** [comment]
Thanks for your help.  That fixed my problem.
